from typing import TypedDict


class AnalysisState(TypedDict, total=False):
    file_path: str

    summary: dict

    anomalies: dict

    insights: list[str]

    recommendations: str #should be string since it's generated by Gemini

    risk_level: str

    executive_summary: str